// src/cashier_frontend/src/components/link-details/amount-action-buttons.tsx
import { Button } from "@/components/ui/button";
import { ReactNode } from "react";

interface AmountActionButtonData {
    content?: ReactNode;
    action: () => void;
}

interface AmountActionButtons {
    data: AmountActionButtonData[];
    isDisabled?: boolean;
}

export function AmountActionButtons({ data, isDisabled }: AmountActionButtons) {
    return (
        <div className="flex justify-between w-full mx-auto">
            {data.map(({ content, action }, index) => (
                <Button
                    key={index}
                    type="button"
                    variant="outline"
                    size="sm"
                    className="asset-amount-percentage-button"
                    onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        console.log("Button clicked");
                        action();
                    }}
                    disabled={isDisabled}
                >
                    {content}
                </Button>
            ))}
        </div>
    );
}

// src/cashier_frontend_new/src/modules/creationLink/components/tiplink/AmountActionButtons.svelte
<script lang="ts">
  import Button from "$lib/shadcn/components/ui/button/button.svelte";

  type AmountActionButtonData = {
    content?: string;
    action: () => void;
  };

  type Props = {
    data: AmountActionButtonData[];
    isDisabled?: boolean;
  };

  let { data, isDisabled = false }: Props = $props();
</script>

<div class="flex justify-between w-full mx-auto gap-2">
  {#each data as { content, action }, index}
    <Button
      type="button"
      variant="outline"
      size="icon"
      class="asset-amount-percentage-button focus:border-green focus:text-green focus:bg-white h-9 w-9 rounded-full"
      onclick={(e) => {
        e.preventDefault();
        e.stopPropagation();
        action();
      }}
      disabled={isDisabled}
    >
      {content}
    </Button>
  {/each}
</div>
