// src/cashier_frontend/src/components/link-item.tsx
import { LINK_STATUS } from "@/constants/otherConst";
import { LINK_STATE } from "@/services/types/enum";
import { LinkDetailModel } from "@/services/types/link.service.types";

interface LinkData {
    title: string;
    status: string;
    image: string;
    state: any;
}

export function StateBadge({ state }: { state: any }) {
    if (state === LINK_STATE.ADD_ASSET) {
        return (
            <div className="text-sm text-gray-500 font-xs text-green rounded-full px-2 bg-lightyellow text-yellow">
                {LINK_STATUS.PENDING_DETAIL}
            </div>
        );
    }

    if (state === LINK_STATE.CREATE_LINK) {
        return (
            <div className="text-sm font-normal rounded-full px-2 bg-lightpurple text-[#3648A1]">
                {LINK_STATUS.PENDING_PREVIEW}
            </div>
        );
    }

    if (state === LINK_STATE.ACTIVE) {
        return (
            <div className="text-sm text-gray-500 font-xs text-green rounded-full px-2 bg-green text-white">
                {LINK_STATUS.ACTIVE}
            </div>
        );
    }

    if (state === LINK_STATE.INACTIVE) {
        return (
            <div className="text-sm text-gray-500 font-xs text-green rounded-full px-2 bg-gray-200 text-gray-700">
                {LINK_STATUS.INACTIVE}
            </div>
        );
    }

    if (state === LINK_STATE.CHOOSETEMPLATE) {
        return (
            <div className="text-sm text-gray-500 font-xs text-green rounded-full px-2 bg-lightgreen">
                {LINK_STATUS.NEW}
            </div>
        );
    }
}

export default function LinkItem({ link }: { link: LinkDetailModel }) {
    console.log(link);
    return (
        <div className="w-full flex justify-between items-center my-5">
            <div className="flex gap-x-5 items-center">
                {link.image ? (
                    <img src={link.image} alt="link" className="w-10 h-10 rounded-sm" />
                ) : (
                    <div className="w-10 h-10 rounded-sm bg-gray-200"></div>
                )}
            </div>
            <div className="flex items-center justify-between grow ml-3">
                <h3 className="text-lg font-base">
                    {link.title.length > 0 ? link.title : "No title"}
                </h3>
                <StateBadge state={link.state} />
            </div>
        </div>
    );
}

// src/cashier_frontend_new/src/modules/app/components/linksPage/LinkItem.svelte
<script lang="ts">
  import {
    LinkType,
    type LinkTypeValue,
  } from "$modules/links/types/link/linkType";
  import {
    LinkState,
    type LinkStateValue,
  } from "$modules/links/types/link/linkState";
  import { assertUnreachable } from "$lib/rsMatch";

  type Props = {
    title: string;
    linkType: LinkTypeValue;
    state: LinkStateValue;
    onClick: (event: MouseEvent) => void;
  };

  let { title, linkType, state, onClick }: Props = $props();

  console.log("LinkItem props:", { title, linkType, state });

  function getStatusLabel(state: LinkStateValue): string {
    switch (state) {
      case LinkState.CREATE_LINK:
        return "Draft";
      case LinkState.ACTIVE:
        return "Active";
      case LinkState.INACTIVE:
        return "Inactive";
      case LinkState.INACTIVE_ENDED:
        return "Inactive";
      default:
        assertUnreachable(state);
    }
  }

  function getStatusClasses(state: LinkStateValue): string {
    switch (state) {
      case LinkState.CREATE_LINK:
        return "bg-lightyellow text-yellow";
      case LinkState.ACTIVE:
        return "bg-green text-white";
      case LinkState.INACTIVE:
      case LinkState.INACTIVE_ENDED:
        return "bg-gray-200 text-gray-700";
      default:
        assertUnreachable(state);
    }
  }

  function getLinkDefaultAvatar(linkType: LinkTypeValue): string {
    switch (linkType) {
      case LinkType.TIP:
        return "/tip-link-default.svg";
      case LinkType.AIRDROP:
        return "/airdrop-default.svg";
      case LinkType.TOKEN_BASKET:
        return "/token-basket-default.svg";
      case LinkType.RECEIVE_PAYMENT:
        return "/receive-payment-default.svg";
      default:
        assertUnreachable(linkType);
    }
  }
</script>

<button onclick={onClick} class="block w-full text-left">
  <div class="w-full flex justify-between items-center my-3">
    <div class="flex gap-x-5 items-center">
      <div
        class="flex items-center justify-center w-[32px] h-[32px] bg-lightgreen rounded-[6px]"
      >
        <img
          alt="link"
          class="w-[18px] h-[18px] rounded-sm"
          src={getLinkDefaultAvatar(linkType)}
        />
      </div>
    </div>
    <div class="flex items-center justify-between grow ml-3">
      <div class="flex flex-col items-start justify-center">
        <h3 class="text-[14px] font-medium">{title}</h3>
      </div>
      {#if state}
        <div
          class="text-xs font-xs rounded-full px-2 py-1 {getStatusClasses(
            state,
          )}"
        >
          {getStatusLabel(state)}
        </div>
      {/if}
    </div>
  </div>
</button>
