// src/cashier_frontend/src/components/asset-button.tsx
// Copyright (c) 2025 Cashier Protocol Labs
// Licensed under the MIT License (see LICENSE file in the project root)

import React, { useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { UsdSwitch } from "./link-details/usd-switch";
import { AmountActionButtons } from "./link-details/amount-action-buttons";
import { FungibleToken } from "@/types/fungible-token.speculative";
import { convertDecimalBigIntToNumber } from "@/utils";
import { formatNumber } from "@/utils/helpers/currency";

interface AssetButtonProps {
  handleClick: () => void;
  text: string;
  childrenNode?: React.ReactNode;
  tokenValue?: string;
  usdValue?: string;
  onInputChange?: (value: string) => void;
  isUsd?: boolean;
  token?: FungibleToken;
  onToggleUsd?: (value: boolean) => void;
  canConvert?: boolean;
  tokenDecimals?: number;
  showPresetButtons?: boolean;
  presetButtons?: Array<{ content: string; action: () => void }>;
  isDisabled?: boolean;
  showMaxButton?: boolean;
  onMaxClick?: () => void;
  showInput?: boolean;
  isTip?: boolean;
}

const AssetButton: React.FC<AssetButtonProps> = ({
  text,
  handleClick,
  childrenNode,
  tokenValue,
  usdValue,
  onInputChange,
  isUsd = false,
  token,
  onToggleUsd,
  canConvert = false,
  tokenDecimals = 8,
  showPresetButtons = false,
  presetButtons = [],
  isDisabled = false,
  isTip,
  showInput = true,
}) => {
  // Determine which value to display based on isUsd flag
  const displayValue = isUsd ? usdValue : tokenValue;

  // Local state for immediate UI feedback
  const [localInputValue, setLocalInputValue] = useState<string>(
    displayValue || "",
  );

  // Update local state when props change
  React.useEffect(() => {
    setLocalInputValue(displayValue || "");
  }, [displayValue]);

  // Ref for debounce timer
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Validate and format input for crypto amounts
  const handleInputChange = (value: string) => {
    // Allow only digits and at most one decimal point (period or comma)
    let sanitized = "";
    let hasDecimal = false;

    for (let i = 0; i < value.length; i++) {
      const char = value[i];

      // Allow digits
      if (/[0-9]/.test(char)) {
        sanitized += char;
      }
      // Allow only one decimal point (either . or ,)
      else if ((char === "." || char === ",") && !hasDecimal) {
        sanitized += "."; // Always store as period internally
        hasDecimal = true;
      }
    }

    // Update local state immediately for UI feedback
    setLocalInputValue(sanitized);

    // Clear any existing timer
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current);
    }

    // Set a new timer to call onInputChange after 500ms
    debounceTimerRef.current = setTimeout(() => {
      onInputChange?.(sanitized);
    }, 1000);
  };

  // Format the display value to avoid scientific notation
  const formatDisplayValue = (value: string): string => {
    if (!value) return "";

    // Parse the value as a number
    const num = parseFloat(value);

    // If it's a valid number but would display as scientific notation
    if (!isNaN(num) && Math.abs(num) > 0 && Math.abs(num) < 0.0001) {
      // Convert to decimal string without scientific notation
      return num.toLocaleString("fullwide", {
        useGrouping: false,
        maximumFractionDigits: 20,
      });
    }

    return value;
  };

  return (
    <div className="flex flex-col w-full relative">
      {/* Asset selector with input */}
      <div className={cn("input-field-asset flex items-center relative")}>
        {childrenNode ? (
          <span className="flex items-center w-full relative">
            <span onClick={handleClick} className="text-left w-fit">
              {childrenNode}
            </span>
            <div className="flex w-fit items-center ml-auto relative">
              {showInput && (
                <>
                  <div className="relative flex items-center">
                    {isUsd && (
                      <span className="text-[14px] text-gray-400 mr-1">$</span>
                    )}
                    <input
                      id={`asset-input-${token?.address}`}
                      value={formatDisplayValue(localInputValue)}
                      onChange={(e) => handleInputChange(e.target.value)}
                      type="text"
                      inputMode="decimal"
                      className="w-auto min-w-[30px] ml-auto text-end text-[14px] font-normal placeholder:text-[#D9D9D9] focus:outline-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                      placeholder="0"
                      style={{
                        width: `${Math.max((formatDisplayValue(localInputValue) || "").length * 9, 30)}px`,
                        maxWidth: "250px",
                        position: "relative",
                        zIndex: 0,
                      }}
                    />
                    {/* Overlay rendered after input, with higher z-index */}
                    <div
                      onClick={() => {
                        const input = document.getElementById(
                          `asset-input-${token?.address}`,
                        );
                        input?.focus();
                      }}
                      className="absolute right-0 top-0 h-full w-[100px] z-20 cursor-pointer"
                    />
                  </div>
                </>
              )}
            </div>
          </span>
        ) : (
          <span className="flex items-center">
            <span className="flex-grow text-left">{text}</span>
          </span>
        )}
      </div>

      {/* Balance and USD Switch */}
      {token && (
        <div className="flex px-1 items-center justify-between mt-1.5">
          <p className="text-[10px] font-light text-grey-400/60">
            Balance{" "}
            {token?.amount
              ? formatNumber(
                  convertDecimalBigIntToNumber(
                    token.amount,
                    token.decimals,
                  ).toString(),
                )
              : 0}{" "}
            {token?.symbol}
          </p>

          {onToggleUsd && (
            <UsdSwitch
              token={token}
              amount={parseFloat(tokenValue || "0") || 0}
              symbol={token?.name ?? ""}
              isUsd={isUsd}
              onToggle={onToggleUsd}
              canConvert={canConvert}
              tokenDecimals={tokenDecimals}
              usdDecimals={4}
            />
          )}
        </div>
      )}

      {/* Preset Buttons */}
      {showPresetButtons && presetButtons.length > 0 && canConvert && isTip && (
        <div className="mt-8">
          <AmountActionButtons data={presetButtons} isDisabled={isDisabled} />
        </div>
      )}
    </div>
  );
};

export default AssetButton;

// src/cashier_frontend_new/src/modules/creationLink/components/shared/AssetButton.svelte
<script lang="ts">
  import type { TokenWithPriceAndBalance } from "$modules/token/types";
  import { parseBalanceUnits } from "$modules/shared/utils/converter";
  import { formatNumber } from "$modules/shared/utils/formatNumber";
  import { locale } from "$lib/i18n";
  import { toast } from "svelte-sonner";
  import UsdSwitch from "./UsdSwitch.svelte";
  import AmountActionButtons from "./AmountActionButtons.svelte";
  import type { Snippet } from "svelte";
  import { formatDisplayValue } from "$modules/creationLink/utils/formatDisplayValue";
  import { sanitizeNumericInput } from "$modules/creationLink/utils/sanitize-numeric-input";

  type PresetButton = {
    content: string;
    action: () => void;
  };

  type Props = {
    text: string;
    tokenValue?: string;
    usdValue?: string;
    onInputChange?: (value: string) => void;
    isUsd?: boolean;
    token?: TokenWithPriceAndBalance | null;
    onToggleUsd?: (value: boolean) => void;
    canConvert?: boolean;
    showPresetButtons?: boolean;
    presetButtons?: PresetButton[];
    isDisabled?: boolean;
    showInput?: boolean;
    isTip?: boolean;
    maxBalanceWithFee?: number;
    children?: Snippet<[]>;
  };

  let {
    text,
    children,
    tokenValue = $bindable(""),
    usdValue = $bindable(""),
    onInputChange,
    isUsd = false,
    token,
    onToggleUsd,
    canConvert = false,
    showPresetButtons = false,
    presetButtons = [],
    isDisabled = false,
    showInput = true,
    isTip = false,
    maxBalanceWithFee = 0,
  }: Props = $props();

  // Display value derived from bound props - no local state needed
  const displayValue = $derived(isUsd ? usdValue : tokenValue);

  function handleKeyDown(e: KeyboardEvent) {
    if (
      [
        "Backspace",
        "Delete",
        "Tab",
        "Escape",
        "Enter",
        "ArrowLeft",
        "ArrowRight",
        "ArrowUp",
        "ArrowDown",
      ].includes(e.key)
    ) {
      return;
    }

    if (e.ctrlKey || e.metaKey) {
      return;
    }

    // Prevent minus sign (-) - never allow negative numbers
    if (e.key === "-" || e.key === "Minus") {
      e.preventDefault();
      return;
    }

    const char = e.key;
    const currentValue = displayValue;
    const hasDecimal = currentValue.includes(".") || currentValue.includes(",");

    if (!/[0-9]/.test(char) && char !== "." && char !== ",") {
      e.preventDefault();
      return;
    }

    if ((char === "." || char === ",") && hasDecimal) {
      e.preventDefault();
      return;
    }
  }

  const maxBalance = $derived(
    token?.balance ? parseBalanceUnits(token.balance, token.decimals) : 0,
  );

  // Update bound value directly, debounce side effects
  function updateValue(sanitized: string) {
    if (isUsd) {
      usdValue = sanitized;
    } else {
      tokenValue = sanitized;
    }
  }

  function handleInput(value: string) {
    const sanitized = sanitizeNumericInput(value);

    // Update bound value immediately for responsive UI
    updateValue(sanitized);

    // Call onInputChange immediately for reactive conversion (USD <-> token)
    // This ensures the input is reactive and updates instantly
    onInputChange?.(sanitized);
  }

  // Get max USD value (if token has price) - using maxBalanceWithFee
  const maxUsdValue = $derived(
    token?.priceUSD && token.priceUSD > 0
      ? maxBalanceWithFee * token.priceUSD
      : 0,
  );

  function handleBlur() {
    if (!token || !displayValue) return;

    const inputValue = parseFloat(displayValue);
    if (isNaN(inputValue) || inputValue <= 0) return;

    const hasInsufficientFunds =
      !isFinite(maxBalanceWithFee) ||
      maxBalanceWithFee <= 0 ||
      maxBalance <= 0 ||
      !isFinite(maxBalance);

    if (hasInsufficientFunds) {
      return;
    }

    let exceedsBalance = false;
    let maxValue = 0;
    let maxValueStr = "";

    if (isUsd) {
      if (token.priceUSD && token.priceUSD > 0 && inputValue > maxUsdValue) {
        exceedsBalance = true;
        maxValue = maxUsdValue;
        maxValueStr = maxUsdValue.toFixed(2).replace(/\.?0+$/, "");
      }
    } else {
      if (inputValue > maxBalanceWithFee) {
        exceedsBalance = true;
        maxValue = maxBalanceWithFee;
        maxValueStr = maxBalanceWithFee.toString();
      }
    }

    if (exceedsBalance) {
      updateValue(maxValueStr);
      onInputChange?.(maxValueStr);

      const symbol = isUsd ? "USD" : token.symbol;
      const message = locale
        .t("links.linkForm.addAsset.maxBalanceExceeded")
        .replace("{{max}}", formatNumber(maxValue))
        .replace("{{symbol}}", symbol);
      toast.info(message, {
        duration: 3000,
      });
    }
  }

  const inputWidth = $derived(
    `${Math.max((formatDisplayValue(displayValue) || "").length * 9, 30)}px`,
  );

  const balanceDisplay = $derived(
    token?.balance
      ? formatNumber(parseBalanceUnits(token.balance, token.decimals))
      : "0",
  );

  function focusInput() {
    const input = document.getElementById(
      `asset-input-${token?.address || "default"}`,
    );
    input?.focus();
  }

  function handleInputAreaKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      focusInput();
    }
  }
</script>

<div class="flex flex-col w-full relative">
  <!-- Asset selector with input -->
  <div
    class="input-field-asset flex items-center relative rounded-md border border-gray-300 hover:border-green focus:border-green focus:ring-0 py-2 px-3 focus:outline-none"
  >
    {#if children}
      <div class="flex items-center w-full relative">
        <div class="text-left w-fit max-w-[calc(100%-120px)]">
          {@render children()}
        </div>
        <div class="flex w-fit items-center ml-auto relative">
          {#if showInput}
            <div class="relative flex items-center">
              {#if isUsd}
                <span class="text-[14px] text-gray-400 mr-1">$</span>
              {/if}
              <input
                id="asset-input-{token?.address || 'default'}"
                value={formatDisplayValue(displayValue)}
                oninput={(e) => handleInput(e.currentTarget.value)}
                onkeydown={handleKeyDown}
                onblur={handleBlur}
                type="number"
                class="w-auto min-w-[30px] ml-auto text-end text-[14px] font-normal placeholder:text-[#D9D9D9] focus:outline-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                style="width: {inputWidth}; max-width: 92px; position: relative; z-index: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"
                placeholder="0"
                min={0}
                inputmode="decimal"
              />
              <div
                role="button"
                tabindex="0"
                onclick={focusInput}
                onkeydown={handleInputAreaKeyDown}
                class="absolute right-0 top-0 h-full w-[90px] z-20 cursor-pointer"
              ></div>
            </div>
          {/if}
        </div>
      </div>
    {:else}
      <span class="flex items-center">
        <span class="flex-grow text-left">{text}</span>
      </span>
    {/if}
  </div>

  <!-- Balance and USD Switch -->
  {#if token}
    <div class="flex px-1 items-center justify-between mt-1.5">
      <p class="text-[10px] font-light text-grey-400/60">
        {locale.t("links.linkForm.addAsset.balance")}
        {balanceDisplay}
        {token?.symbol}
      </p>

      {#if onToggleUsd}
        <UsdSwitch
          {token}
          amount={parseFloat(tokenValue || "0") || 0}
          symbol={token?.name ?? ""}
          {isUsd}
          onToggle={onToggleUsd}
          {canConvert}
        />
      {/if}
    </div>
  {/if}

  <!-- Preset Buttons -->
  {#if showPresetButtons && presetButtons.length > 0 && canConvert && isTip}
    <div class="mt-8">
      <AmountActionButtons data={presetButtons} {isDisabled} />
    </div>
  {/if}
</div>
